[package]
name = "zbessel-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "zbessel_rs"
crate-type = ["lib"]


[dependencies]
num-complex = "0.4"

[build-dependencies]
bindgen = "0.70"
cc = "1.0"
